name                = "hello-worker-2"
main                = "src/index.ts"
compatibility_date  = "2024-04-04"
compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "HELLO1"
service = "hello-worker-1"

[[services]]
binding = "GREET"
service = "worker-rust"
